import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage {
  english('English', 'en'),
  vietnamese('Vietnamese', 'vi'),
  japanese('Japanese', 'ja');

  final String label;
  final String code;

  const AppLanguage(this.label, this.code);
}

class LanguageController extends ChangeNotifier {
  static const String _storageKey = 'app_language';

  AppLanguage _language = AppLanguage.english;

  LanguageController() {
    _load();
  }

  AppLanguage get language => _language;
  String get label => _language.label;

  Future<void> setLanguage(AppLanguage value) async {
    _language = value;
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_storageKey, value.code);
  }

  Future<void> _load() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString(_storageKey);
    final saved = AppLanguage.values.where((item) => item.code == code);
    if (saved.isEmpty) return;

    _language = saved.first;
    notifyListeners();
  }

  String text(String key) {
    return _localizedText[_language]?[key] ??
        _localizedText[AppLanguage.english]?[key] ??
        key;
  }
}

const Map<AppLanguage, Map<String, String>> _localizedText = {
  AppLanguage.english: {
    'home': 'Home',
    'history': 'History',
    'budget': 'Budget',
    'insights': 'Insights',
    'profile': 'Profile',
    'profile_title': 'Profile',
    'account_settings': 'ACCOUNT SETTINGS',
    'dark_mode': 'Dark Mode',
    'notifications': 'Notifications',
    'currency': 'Currency',
    'language': 'Language',
    'ai_insights': 'AI Insights',
    'logout': 'Logout',
    'edit_profile': 'Edit Profile',
    'change_avatar': 'Change avatar',
    'on': 'On',
    'off': 'Off',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'choose_language': 'Choose the app language preference',
    'choose_currency': 'Choose display currency for your profile',
    'avatar': 'Avatar',
    'avatar_subtitle': 'Choose how your profile should look',
    'gallery': 'Gallery',
    'camera': 'Camera',
    'template_avatar': 'Or choose a template avatar',
    'edit_profile_title': 'Edit profile',
    'edit_profile_subtitle': 'Update your display information',
    'name': 'Name',
    'email': 'Email',
    'cancel': 'Cancel',
    'save': 'Save',
    'logout_subtitle': 'You can sign in again anytime',
    'notifications_subtitle': 'Manage app reminders on this device',
    'budget_reminders': 'Budget reminders',
    'enable_notifications': 'Enable Notifications',
    'ai_subtitle': 'Control smart suggestions in the app',
    'personalized_analysis': 'Personalized analysis',
    'ai_enabled_note': 'AI insights are enabled for your spending data.',
    'ai_disabled_note': 'AI insights are paused on this device.',
    'enable_ai': 'Enable AI Insights',
    'welcome_back': 'Welcome back,',
    'available_balance': 'Available Balance',
    'details': 'Details',
    'income': 'Income',
    'expenses': 'Expenses',
    'spending_summary': 'Spending Summary',
    'last_7_days': 'Last 7 Days',
    'recent_transactions': 'Recent Transactions',
    'see_all': 'See All',
    'balance_details': 'Balance details',
    'income_this_month': 'Income this month',
    'expense_this_month': 'Expense this month',
    'month_balance': 'Month balance',
    'view_transaction_history': 'View transaction history',
    'no_month_activity':
        'There are no income or expense transactions this month yet.',
    'no_month_income_rate':
        'There is no income this month to calculate a saving rate.',
    'keeping_income': 'You are keeping about {rate}% of this month\'s income.',
    'month_left':
        'This month you have {amount} left before adding previous balances.',
    'month_short':
        'This month is short by {amount}; previous balances are covering the gap.',
    'transaction_history': 'Transaction History',
    'user_not_logged_in': 'User is not logged in',
    'error_prefix': 'Error',
    'no_transactions': 'No transactions found.',
    'no_filter_results': 'No transactions match your filters.',
    'search_transactions': 'Search description, category, note...',
    'all': 'All',
    'expense': 'Expense',
    'income_type': 'Income',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'edit': 'Edit',
    'delete': 'Delete',
    'edit_transaction': 'Edit transaction',
    'description': 'Description',
    'category': 'Category',
    'account': 'Account',
    'amount': 'Amount',
    'notes': 'Notes',
    'save_changes': 'Save changes',
    'amount_gt_zero': 'Amount must be greater than 0.',
    'delete_transaction': 'Delete transaction?',
    'delete_warning': 'This action cannot be undone.',
    'carried': 'Carried',
    'monthly_budget': 'Monthly Budget',
    'budget_tools': 'Budget tools',
    'budget_tools_subtitle': 'Manage plans beyond monthly limits',
    'saving_goals': 'Saving Goals',
    'saving_goals_subtitle':
        'Track targets like trips, laptop, emergency fund.',
    'recurring_transactions': 'Recurring Transactions',
    'recurring_subtitle': 'Plan salary, rent, subscriptions, and fixed bills.',
    'category_budgets': 'Category Budgets',
    'no_budget_data': 'No budget data found.',
    'no_categories': 'No categories yet',
    'no_categories_subtitle':
        'Add categories from Add Transaction to set monthly limits.',
    'monthly_spending_limit': 'Monthly spending limit',
    'monthly_limit': 'Monthly limit',
    'budget_limit_gt_zero': 'Budget limit must be greater than 0.',
    'spent_this_month': 'Spent this month',
    'planned_of_budget': 'of {amount} planned',
    'set_category_budgets': 'Set category budgets to track limits',
    'no_monthly_limits': 'No monthly limits yet',
    'new_saving_goal': 'New Saving Goal',
    'edit_goal': 'Edit Goal',
    'goal_sheet_subtitle': 'Build progress you can actually see',
    'goal_name': 'Goal name',
    'target': 'Target',
    'saved': 'Saved',
    'note': 'Note',
    'emergency_fund': 'Emergency fund',
    'optional': 'Optional',
    'enter_goal_name': 'Please enter a goal name.',
    'target_gt_zero': 'Target amount must be greater than 0.',
    'saved_not_negative': 'Saved amount cannot be less than 0.',
    'add_money': 'Add Money',
    'added_gt_zero': 'Added amount must be greater than 0.',
    'add': 'Add',
    'add_goal': 'Add Goal',
    'saving_progress': 'Saving progress',
    'of_target': 'of {amount} target',
    'goals': 'Goals',
    'remaining': 'Remaining',
    'completed': 'Completed',
    'empty_goal_title': 'Make the next target visible',
    'empty_goal_subtitle':
        'Track a laptop, trip, emergency fund, or anything you want to save for.',
    'no_target_date': 'No target date',
    'add_transaction': 'Add Transaction',
    'transaction_type': 'Transaction Type',
    'select_category': 'Select Category',
    'custom_category': 'Add custom category',
    'date': 'Date',
    'payment_method': 'Payment Method',
    'notes_optional': 'Notes (Optional)',
    'enter_description': 'Enter description',
    'add_note': 'Add a note...',
    'save_transaction': 'Save Transaction',
    'main_card': 'Main Card',
    'cash': 'Cash',
    'recurring': 'Recurring',
    'new_recurring': 'New recurring',
    'edit_recurring': 'Edit recurring',
    'frequency': 'Frequency',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'active': 'Active',
    'required_info': 'Please enter all required information.',
    'no_recurring': 'No recurring transactions',
    'no_recurring_subtitle':
        'Create salary, rent, subscriptions, or other repeated transactions.',
    'add_recurring': 'Add Recurring Transaction',
    'estimated_monthly_impact': 'Estimated monthly impact',
    'ai_off': 'AI Insights is off',
    'ai_off_body':
        'Smart analysis, spending alerts, and AI chat are paused until you turn this back on.',
    'turn_on_ai': 'Turn On AI Insights',
    'no_insight_data': 'No insight data found.',
    'spending_alert': 'Spending Alert',
    'this_month': 'This month',
    'analyze_habits': 'Analyze habits',
    'ask_ai': 'Ask AI',
    'saving_suggestion': 'Saving Suggestion',
    'create_saving_plan': 'Create Saving Plan',
    'this_month_forecast': 'This Month Forecast',
    'spent': 'Spent',
    'forecast': 'Forecast',
    'ai_assistant': 'AI Assistant',
    'ask_placeholder': 'Ask about spending, forecasts, or saving...',
    'am_i_overspending': 'Am I overspending?',
    'which_category_cut': 'Which category should I cut?',
    'action_canceled': 'Action canceled. Nothing was saved.',
    'saved_to_app': 'Saved to the app.',
    'app_name': 'AI Expense Manager',
    'smart_financial_control': 'SMART FINANCIAL CONTROL',
    'analyzing_transactions': 'Analysing transactions...',
    'skip': 'Skip',
    'money_flow': 'Money Flow',
    'save_short': 'Save',
    'food': 'Food',
    'your_money_smarter': 'Your Money, Smarter',
    'onboarding_subtitle':
        'Experience the future of personal finance with AI-powered tracking.',
    'get_started': 'Get Started',
    'welcome_back_title': 'Welcome Back',
    'login_subtitle': 'Log in to manage your finances with AI',
    'password': 'Password',
    'forgot_password': 'Forgot password?',
    'enter_password': 'Enter your password',
    'log_in': 'Log In',
    'or_continue_with': 'Or continue with',
    'no_account': 'Don\'t have an account? ',
    'register_now': 'Register now',
    'create_account': 'Create Account',
    'join_app': 'Join AI Expense Manager',
    'register_subtitle':
        'Start tracking your finances smarter with AI-driven insights.',
    'full_name': 'Full Name',
    'enter_full_name': 'Enter your full name',
    'email_address': 'Email Address',
    'confirm_password': 'Confirm Password',
    'repeat_password': 'Repeat your password',
    'terms_text':
        'By registering, you agree to our Terms of Service and Privacy Policy.',
    'register': 'Register',
    'already_account_login': 'Already have an account? Login',
    'please_enter_email_password': 'Please enter email and password',
    'email_password_incorrect': 'Email or password incorrect',
    'please_fill_all_fields': 'Please fill all fields',
    'password_mismatch': 'Password does not match',
    'accept_terms': 'Please accept terms',
    'register_failed': 'Register failed',
    'reset_password': 'Reset Password',
    'forgot_password_title': 'Forgot Password?',
    'reset_password_body':
        'Enter your account email and choose a new password.',
    'reset_link_sent': 'Reset link sent (demo)',
    'send_reset_link': 'Send Reset Link',
    'reset_success':
        'Password updated successfully. You can now log in with the new password.',
    'new_password': 'New password',
    'update_password': 'Update Password',
    'password_reset_success': 'Password updated successfully.',
    'email_not_found': 'No account found with this email.',
    'invalid_email': 'Please enter a valid email address.',
    'weak_password': 'Password must be at least 6 characters.',
    'reset_failed': 'Could not reset password. Please try again.',
    'account_created': 'Account Created!',
    'account_created_body':
        'Your AI Expense Manager account is ready.\nStart tracking your finances smarter today.',
    'confirm': 'Confirm',
    'action': 'Action',
    'set_budget': 'Set budget',
    'add_saving_goal': 'Add saving goal',
    'financial_scope_reply':
        'I only help with personal finance topics like spending, income, budget, savings, transactions, forecasts, or financial goals. Please ask me something in that area.',
  },
  AppLanguage.vietnamese: {
    'home': 'Trang chủ',
    'history': 'Lịch sử',
    'budget': 'Ngân sách',
    'insights': 'Phân tích',
    'profile': 'Hồ sơ',
    'profile_title': 'Hồ sơ',
    'account_settings': 'CÀI ĐẶT TÀI KHOẢN',
    'dark_mode': 'Chế độ tối',
    'notifications': 'Thông báo',
    'currency': 'Tiền tệ',
    'language': 'Ngôn ngữ',
    'ai_insights': 'Phân tích AI',
    'logout': 'Đăng xuất',
    'edit_profile': 'Chỉnh sửa hồ sơ',
    'change_avatar': 'Đổi avatar',
    'on': 'Bật',
    'off': 'Tắt',
    'enabled': 'Đã bật',
    'disabled': 'Đã tắt',
    'choose_language': 'Chọn ngôn ngữ hiển thị cho ứng dụng',
    'choose_currency': 'Chọn tiền tệ hiển thị cho hồ sơ',
    'avatar': 'Avatar',
    'avatar_subtitle': 'Chọn giao diện hồ sơ của bạn',
    'gallery': 'Thư viện',
    'camera': 'Camera',
    'template_avatar': 'Hoặc chọn ảnh mẫu',
    'edit_profile_title': 'Chỉnh sửa hồ sơ',
    'edit_profile_subtitle': 'Cập nhật thông tin hiển thị',
    'name': 'Tên',
    'email': 'Email',
    'cancel': 'Hủy',
    'save': 'Lưu',
    'logout_subtitle': 'Bạn có thể đăng nhập lại bất cứ lúc nào',
    'notifications_subtitle': 'Quản lý nhắc nhở trên thiết bị này',
    'budget_reminders': 'Nhắc nhở ngân sách',
    'enable_notifications': 'Bật thông báo',
    'ai_subtitle': 'Điều khiển gợi ý thông minh trong app',
    'personalized_analysis': 'Phân tích cá nhân hóa',
    'ai_enabled_note': 'AI insights đang bật cho dữ liệu chi tiêu.',
    'ai_disabled_note': 'AI insights đang tạm dừng trên thiết bị này.',
    'enable_ai': 'Bật AI Insights',
    'welcome_back': 'Chào mừng trở lại,',
    'available_balance': 'Số dư khả dụng',
    'details': 'Chi tiết',
    'income': 'Thu nhập',
    'expenses': 'Chi tiêu',
    'spending_summary': 'Tóm tắt chi tiêu',
    'last_7_days': '7 ngày gần đây',
    'recent_transactions': 'Giao dịch gần đây',
    'see_all': 'Xem tất cả',
    'balance_details': 'Chi tiết số dư',
    'income_this_month': 'Thu nhập tháng này',
    'expense_this_month': 'Chi tiêu tháng này',
    'month_balance': 'Số dư tháng',
    'view_transaction_history': 'Xem lịch sử giao dịch',
    'no_month_activity': 'Tháng này chưa có giao dịch thu hoặc chi.',
    'no_month_income_rate':
        'Tháng này chưa có thu nhập để tính tỷ lệ tiết kiệm.',
    'keeping_income': 'Bạn đang giữ lại khoảng {rate}% thu nhập tháng này.',
    'month_left': 'Tháng này bạn còn {amount} trước khi cộng số dư cũ.',
    'month_short': 'Tháng này thiếu {amount}; số dư cũ đang bù phần thiếu.',
    'transaction_history': 'Lịch sử giao dịch',
    'user_not_logged_in': 'Người dùng chưa đăng nhập',
    'error_prefix': 'Lỗi',
    'no_transactions': 'Chưa có giao dịch.',
    'no_filter_results': 'Không có giao dịch phù hợp bộ lọc.',
    'search_transactions': 'Tìm mô tả, danh mục, ghi chú...',
    'all': 'Tất cả',
    'expense': 'Chi tiêu',
    'income_type': 'Thu nhập',
    'today': 'Hôm nay',
    'yesterday': 'Hôm qua',
    'edit': 'Sửa',
    'delete': 'Xóa',
    'edit_transaction': 'Sửa giao dịch',
    'description': 'Mô tả',
    'category': 'Danh mục',
    'account': 'Tài khoản',
    'amount': 'Số tiền',
    'notes': 'Ghi chú',
    'save_changes': 'Lưu thay đổi',
    'amount_gt_zero': 'Số tiền phải lớn hơn 0.',
    'delete_transaction': 'Xóa giao dịch?',
    'delete_warning': 'Thao tác này không thể hoàn tác.',
    'carried': 'Cộng dồn',
    'monthly_budget': 'Ngân sách tháng',
    'budget_tools': 'Công cụ ngân sách',
    'budget_tools_subtitle': 'Quản lý kế hoạch ngoài giới hạn tháng',
    'saving_goals': 'Mục tiêu tiết kiệm',
    'saving_goals_subtitle': 'Theo dõi chuyến đi, laptop, quỹ khẩn cấp.',
    'recurring_transactions': 'Giao dịch định kỳ',
    'recurring_subtitle': 'Lên kế hoạch lương, thuê nhà, hóa đơn cố định.',
    'category_budgets': 'Ngân sách theo danh mục',
    'no_budget_data': 'Không có dữ liệu ngân sách.',
    'no_categories': 'Chưa có danh mục',
    'no_categories_subtitle':
        'Thêm danh mục từ Add Transaction để đặt giới hạn tháng.',
    'monthly_spending_limit': 'Giới hạn chi tiêu tháng',
    'monthly_limit': 'Giới hạn tháng',
    'budget_limit_gt_zero': 'Giới hạn ngân sách phải lớn hơn 0.',
    'spent_this_month': 'Đã chi tháng này',
    'planned_of_budget': 'trong {amount} đã lên kế hoạch',
    'set_category_budgets': 'Đặt ngân sách danh mục để theo dõi giới hạn',
    'no_monthly_limits': 'Chưa có giới hạn tháng',
    'new_saving_goal': 'Mục tiêu mới',
    'edit_goal': 'Sửa mục tiêu',
    'goal_sheet_subtitle': 'Theo dõi tiến độ rõ ràng',
    'goal_name': 'Tên mục tiêu',
    'target': 'Mục tiêu',
    'saved': 'Đã tiết kiệm',
    'note': 'Ghi chú',
    'emergency_fund': 'Quỹ khẩn cấp',
    'optional': 'Tùy chọn',
    'enter_goal_name': 'Vui lòng nhập tên mục tiêu.',
    'target_gt_zero': 'Số tiền mục tiêu phải lớn hơn 0.',
    'saved_not_negative': 'Số tiền đã tiết kiệm không được nhỏ hơn 0.',
    'add_money': 'Thêm tiền',
    'added_gt_zero': 'Số tiền thêm phải lớn hơn 0.',
    'add': 'Thêm',
    'add_goal': 'Thêm mục tiêu',
    'saving_progress': 'Tiến độ tiết kiệm',
    'of_target': 'trong mục tiêu {amount}',
    'goals': 'Mục tiêu',
    'remaining': 'Còn lại',
    'completed': 'Hoàn thành',
    'empty_goal_title': 'Biến mục tiêu tiếp theo thành rõ ràng',
    'empty_goal_subtitle':
        'Theo dõi laptop, chuyến đi, quỹ khẩn cấp hoặc bất kỳ điều gì bạn muốn tiết kiệm.',
    'no_target_date': 'Không có ngày mục tiêu',
    'add_transaction': 'Thêm giao dịch',
    'transaction_type': 'Loại giao dịch',
    'select_category': 'Chọn danh mục',
    'custom_category': 'Thêm danh mục tùy chỉnh',
    'date': 'Ngày',
    'payment_method': 'Phương thức thanh toán',
    'notes_optional': 'Ghi chú (tùy chọn)',
    'enter_description': 'Nhập mô tả',
    'add_note': 'Thêm ghi chú...',
    'save_transaction': 'Lưu giao dịch',
    'main_card': 'Thẻ chính',
    'cash': 'Tiền mặt',
    'recurring': 'Định kỳ',
    'new_recurring': 'Định kỳ mới',
    'edit_recurring': 'Sửa định kỳ',
    'frequency': 'Tần suất',
    'daily': 'Hằng ngày',
    'weekly': 'Hằng tuần',
    'monthly': 'Hằng tháng',
    'active': 'Hoạt động',
    'required_info': 'Vui lòng nhập đầy đủ thông tin.',
    'no_recurring': 'Chưa có giao dịch định kỳ',
    'no_recurring_subtitle':
        'Tạo lương, thuê nhà, đăng ký hoặc các giao dịch lặp lại.',
    'add_recurring': 'Thêm giao dịch định kỳ',
    'estimated_monthly_impact': 'Tác động tháng ước tính',
    'ai_off': 'AI Insights đang tắt',
    'ai_off_body':
        'Phân tích thông minh, cảnh báo chi tiêu và chat AI đang tạm dừng.',
    'turn_on_ai': 'Bật AI Insights',
    'no_insight_data': 'Không có dữ liệu phân tích.',
    'spending_alert': 'Cảnh báo chi tiêu',
    'this_month': 'Tháng này',
    'analyze_habits': 'Phân tích thói quen',
    'ask_ai': 'Hỏi AI',
    'saving_suggestion': 'Gợi ý tiết kiệm',
    'create_saving_plan': 'Tạo kế hoạch tiết kiệm',
    'this_month_forecast': 'Dự đoán tháng này',
    'spent': 'Đã chi',
    'forecast': 'Dự đoán',
    'ai_assistant': 'Trợ lý AI',
    'ask_placeholder': 'Hỏi về chi tiêu, dự đoán hoặc tiết kiệm...',
    'am_i_overspending': 'Tôi có đang chi quá tay không?',
    'which_category_cut': 'Nên cắt giảm danh mục nào?',
    'action_canceled': 'Đã hủy thao tác. Không có gì được lưu.',
    'saved_to_app': 'Đã lưu vào app.',
    'app_name': 'AI Expense Manager',
    'smart_financial_control': 'KIỂM SOÁT TÀI CHÍNH THÔNG MINH',
    'analyzing_transactions': 'Đang phân tích giao dịch...',
    'skip': 'Bỏ qua',
    'money_flow': 'Dòng tiền',
    'save_short': 'Tiết kiệm',
    'food': 'Ăn uống',
    'your_money_smarter': 'Tiền của bạn, thông minh hơn',
    'onboarding_subtitle':
        'Trải nghiệm quản lý tài chính cá nhân với AI hỗ trợ theo dõi.',
    'get_started': 'Bắt đầu',
    'welcome_back_title': 'Chào mừng trở lại',
    'login_subtitle': 'Đăng nhập để quản lý tài chính với AI',
    'password': 'Mật khẩu',
    'forgot_password': 'Quên mật khẩu?',
    'enter_password': 'Nhập mật khẩu',
    'log_in': 'Đăng nhập',
    'or_continue_with': 'Hoặc tiếp tục với',
    'no_account': 'Chưa có tài khoản? ',
    'register_now': 'Đăng ký ngay',
    'create_account': 'Tạo tài khoản',
    'join_app': 'Tham gia AI Expense Manager',
    'register_subtitle':
        'Bắt đầu theo dõi tài chính thông minh hơn với phân tích từ AI.',
    'full_name': 'Họ và tên',
    'enter_full_name': 'Nhập họ và tên',
    'email_address': 'Địa chỉ email',
    'confirm_password': 'Xác nhận mật khẩu',
    'repeat_password': 'Nhập lại mật khẩu',
    'terms_text':
        'Khi đăng ký, bạn đồng ý với Điều khoản dịch vụ và Chính sách riêng tư.',
    'register': 'Đăng ký',
    'already_account_login': 'Đã có tài khoản? Đăng nhập',
    'please_enter_email_password': 'Vui lòng nhập email và mật khẩu',
    'email_password_incorrect': 'Email hoặc mật khẩu không đúng',
    'please_fill_all_fields': 'Vui lòng nhập đầy đủ thông tin',
    'password_mismatch': 'Mật khẩu không khớp',
    'accept_terms': 'Vui lòng chấp nhận điều khoản',
    'register_failed': 'Đăng ký thất bại',
    'reset_password': 'Đặt lại mật khẩu',
    'forgot_password_title': 'Quên mật khẩu?',
    'reset_password_body': 'Nhập email tài khoản và chọn mật khẩu mới.',
    'reset_link_sent': 'Đã gửi liên kết đặt lại (demo)',
    'send_reset_link': 'Gửi liên kết đặt lại',
    'reset_success':
        'Đổi mật khẩu thành công. Bạn có thể đăng nhập bằng mật khẩu mới.',
    'new_password': 'Mật khẩu mới',
    'update_password': 'Cập nhật mật khẩu',
    'password_reset_success': 'Đổi mật khẩu thành công.',
    'email_not_found': 'Không tìm thấy tài khoản với email này.',
    'invalid_email': 'Vui lòng nhập email hợp lệ.',
    'weak_password': 'Mật khẩu phải có ít nhất 6 ký tự.',
    'reset_failed': 'Không thể đặt lại mật khẩu. Vui lòng thử lại.',
    'account_created': 'Tạo tài khoản thành công!',
    'account_created_body':
        'Tài khoản AI Expense Manager của bạn đã sẵn sàng.\nHãy bắt đầu theo dõi tài chính thông minh hơn.',
    'confirm': 'Xác nhận',
    'action': 'Thao tác',
    'set_budget': 'Đặt ngân sách',
    'add_saving_goal': 'Thêm mục tiêu tiết kiệm',
    'financial_scope_reply':
        'Mình chỉ hỗ trợ các câu hỏi liên quan đến quản lý tài chính cá nhân như chi tiêu, thu nhập, ngân sách, tiết kiệm, giao dịch, dự đoán chi tiêu hoặc mục tiêu tài chính. Bạn hỏi mình theo hướng đó nhé.',
  },
  AppLanguage.japanese: {
    'home': 'ホーム',
    'history': '履歴',
    'budget': '予算',
    'insights': '分析',
    'profile': 'プロフィール',
    'profile_title': 'プロフィール',
    'account_settings': 'アカウント設定',
    'dark_mode': 'ダークモード',
    'notifications': '通知',
    'currency': '通貨',
    'language': '言語',
    'ai_insights': 'AI分析',
    'logout': 'ログアウト',
    'edit_profile': 'プロフィール編集',
    'change_avatar': 'アバターを変更',
    'on': 'オン',
    'off': 'オフ',
    'enabled': '有効',
    'disabled': '無効',
    'choose_language': 'アプリの表示言語を選択',
    'choose_currency': 'プロフィールの表示通貨を選択',
    'avatar': 'アバター',
    'avatar_subtitle': 'プロフィールの見た目を選択',
    'gallery': 'ギャラリー',
    'camera': 'カメラ',
    'template_avatar': 'またはテンプレートを選択',
    'edit_profile_title': 'プロフィール編集',
    'edit_profile_subtitle': '表示情報を更新',
    'name': '名前',
    'email': 'メール',
    'cancel': 'キャンセル',
    'save': '保存',
    'logout_subtitle': 'いつでも再ログインできます',
    'notifications_subtitle': 'この端末のリマインダーを管理',
    'budget_reminders': '予算リマインダー',
    'enable_notifications': '通知を有効にする',
    'ai_subtitle': 'アプリ内のスマート提案を管理',
    'personalized_analysis': 'パーソナライズ分析',
    'ai_enabled_note': '支出データのAI分析が有効です。',
    'ai_disabled_note': 'この端末ではAI分析が一時停止中です。',
    'enable_ai': 'AI分析を有効にする',
    'welcome_back': 'おかえりなさい、',
    'available_balance': '利用可能残高',
    'details': '詳細',
    'income': '収入',
    'expenses': '支出',
    'spending_summary': '支出サマリー',
    'last_7_days': '過去7日間',
    'recent_transactions': '最近の取引',
    'see_all': 'すべて表示',
    'balance_details': '残高詳細',
    'income_this_month': '今月の収入',
    'expense_this_month': '今月の支出',
    'month_balance': '今月の残高',
    'view_transaction_history': '取引履歴を見る',
    'no_month_activity': '今月はまだ収入または支出の取引がありません。',
    'no_month_income_rate': '今月は貯蓄率を計算する収入がありません。',
    'keeping_income': '今月の収入の約{rate}%を残しています。',
    'month_left': '前月までの残高を加える前に、今月は{amount}残っています。',
    'month_short': '今月は{amount}不足しており、過去の残高で補っています。',
    'transaction_history': '取引履歴',
    'user_not_logged_in': 'ログインしていません',
    'error_prefix': 'エラー',
    'no_transactions': '取引がありません。',
    'no_filter_results': 'フィルターに一致する取引がありません。',
    'search_transactions': '説明、カテゴリ、メモを検索...',
    'all': 'すべて',
    'expense': '支出',
    'income_type': '収入',
    'today': '今日',
    'yesterday': '昨日',
    'edit': '編集',
    'delete': '削除',
    'edit_transaction': '取引を編集',
    'description': '説明',
    'category': 'カテゴリ',
    'account': '口座',
    'amount': '金額',
    'notes': 'メモ',
    'save_changes': '変更を保存',
    'amount_gt_zero': '金額は0より大きくしてください。',
    'delete_transaction': '取引を削除しますか？',
    'delete_warning': 'この操作は元に戻せません。',
    'carried': '繰越',
    'monthly_budget': '月間予算',
    'budget_tools': '予算ツール',
    'budget_tools_subtitle': '月間上限以外の計画を管理',
    'saving_goals': '貯蓄目標',
    'saving_goals_subtitle': '旅行、PC、緊急資金などを追跡します。',
    'recurring_transactions': '定期取引',
    'recurring_subtitle': '給料、家賃、サブスク、固定費を計画します。',
    'category_budgets': 'カテゴリ予算',
    'no_budget_data': '予算データがありません。',
    'no_categories': 'カテゴリがありません',
    'no_categories_subtitle': 'Add Transactionでカテゴリを追加して月間上限を設定します。',
    'monthly_spending_limit': '月間支出上限',
    'monthly_limit': '月間上限',
    'budget_limit_gt_zero': '予算上限は0より大きくしてください。',
    'spent_this_month': '今月の支出',
    'planned_of_budget': '{amount} の計画内',
    'set_category_budgets': 'カテゴリ予算を設定して上限を追跡',
    'no_monthly_limits': '月間上限はまだありません',
    'new_saving_goal': '新しい貯蓄目標',
    'edit_goal': '目標を編集',
    'goal_sheet_subtitle': '進捗を見える化',
    'goal_name': '目標名',
    'target': '目標',
    'saved': '貯蓄済み',
    'note': 'メモ',
    'emergency_fund': '緊急資金',
    'optional': '任意',
    'enter_goal_name': '目標名を入力してください。',
    'target_gt_zero': '目標金額は0より大きくしてください。',
    'saved_not_negative': '貯蓄済み金額は0未満にできません。',
    'add_money': '入金',
    'added_gt_zero': '追加金額は0より大きくしてください。',
    'add': '追加',
    'add_goal': '目標を追加',
    'saving_progress': '貯蓄進捗',
    'of_target': '目標 {amount} のうち',
    'goals': '目標',
    'remaining': '残り',
    'completed': '完了',
    'empty_goal_title': '次の目標を見える化しましょう',
    'empty_goal_subtitle': 'PC、旅行、緊急資金など、貯めたいものを追跡できます。',
    'no_target_date': '目標日なし',
    'add_transaction': '取引を追加',
    'transaction_type': '取引タイプ',
    'select_category': 'カテゴリを選択',
    'custom_category': 'カスタムカテゴリを追加',
    'date': '日付',
    'payment_method': '支払い方法',
    'notes_optional': 'メモ（任意）',
    'enter_description': '説明を入力',
    'add_note': 'メモを追加...',
    'save_transaction': '取引を保存',
    'main_card': 'メインカード',
    'cash': '現金',
    'recurring': '定期',
    'new_recurring': '新しい定期取引',
    'edit_recurring': '定期取引を編集',
    'frequency': '頻度',
    'daily': '毎日',
    'weekly': '毎週',
    'monthly': '毎月',
    'active': '有効',
    'required_info': '必要な情報をすべて入力してください。',
    'no_recurring': '定期取引がありません',
    'no_recurring_subtitle': '給料、家賃、サブスクなどの繰り返し取引を作成します。',
    'add_recurring': '定期取引を追加',
    'estimated_monthly_impact': '推定月間影響',
    'ai_off': 'AI分析はオフです',
    'ai_off_body': 'スマート分析、支出アラート、AIチャットは一時停止中です。',
    'turn_on_ai': 'AI分析をオンにする',
    'no_insight_data': '分析データがありません。',
    'spending_alert': '支出アラート',
    'this_month': '今月',
    'analyze_habits': '習慣を分析',
    'ask_ai': 'AIに聞く',
    'saving_suggestion': '貯蓄提案',
    'create_saving_plan': '貯蓄計画を作成',
    'this_month_forecast': '今月の予測',
    'spent': '支出済み',
    'forecast': '予測',
    'ai_assistant': 'AIアシスタント',
    'ask_placeholder': '支出、予測、貯蓄について質問...',
    'am_i_overspending': '使いすぎていますか？',
    'which_category_cut': 'どのカテゴリを削減すべき？',
    'action_canceled': '操作をキャンセルしました。保存されていません。',
    'saved_to_app': 'アプリに保存しました。',
    'app_name': 'AI Expense Manager',
    'smart_financial_control': 'スマートな家計管理',
    'analyzing_transactions': '取引を分析中...',
    'skip': 'スキップ',
    'money_flow': 'お金の流れ',
    'save_short': '貯蓄',
    'food': '食費',
    'your_money_smarter': 'お金をもっとスマートに',
    'onboarding_subtitle': 'AIによる記録と分析で、新しい個人財務管理を体験しましょう。',
    'get_started': '始める',
    'welcome_back_title': 'おかえりなさい',
    'login_subtitle': 'AIで家計を管理するためにログイン',
    'password': 'パスワード',
    'forgot_password': 'パスワードをお忘れですか？',
    'enter_password': 'パスワードを入力',
    'log_in': 'ログイン',
    'or_continue_with': 'または次で続行',
    'no_account': 'アカウントをお持ちでないですか？ ',
    'register_now': '今すぐ登録',
    'create_account': 'アカウント作成',
    'join_app': 'AI Expense Managerへようこそ',
    'register_subtitle': 'AI分析で、より賢く家計管理を始めましょう。',
    'full_name': '氏名',
    'enter_full_name': '氏名を入力',
    'email_address': 'メールアドレス',
    'confirm_password': 'パスワード確認',
    'repeat_password': 'パスワードを再入力',
    'terms_text': '登録すると、利用規約とプライバシーポリシーに同意したことになります。',
    'register': '登録',
    'already_account_login': 'すでにアカウントがありますか？ログイン',
    'please_enter_email_password': 'メールとパスワードを入力してください',
    'email_password_incorrect': 'メールまたはパスワードが正しくありません',
    'please_fill_all_fields': 'すべての項目を入力してください',
    'password_mismatch': 'パスワードが一致しません',
    'accept_terms': '利用規約に同意してください',
    'register_failed': '登録に失敗しました',
    'reset_password': 'パスワード再設定',
    'forgot_password_title': 'パスワードをお忘れですか？',
    'reset_password_body': 'アカウントのメールアドレスを入力し、新しいパスワードを設定してください。',
    'reset_link_sent': '再設定リンクを送信しました（デモ）',
    'send_reset_link': '再設定リンクを送信',
    'reset_success': 'パスワードを更新しました。新しいパスワードでログインできます。',
    'new_password': '新しいパスワード',
    'update_password': 'パスワードを更新',
    'password_reset_success': 'パスワードを更新しました。',
    'email_not_found': 'このメールのアカウントが見つかりません。',
    'invalid_email': '有効なメールアドレスを入力してください。',
    'weak_password': 'パスワードは6文字以上にしてください。',
    'reset_failed': 'パスワードを再設定できませんでした。もう一度お試しください。',
    'account_created': 'アカウント作成完了！',
    'account_created_body':
        'AI Expense Managerアカウントの準備ができました。\n今日からスマートに家計管理を始めましょう。',
    'confirm': '確認',
    'action': '操作',
    'set_budget': '予算を設定',
    'add_saving_goal': '貯蓄目標を追加',
    'financial_scope_reply':
        '個人の家計管理に関する内容のみサポートします。支出、収入、予算、貯蓄、取引、予測、目標について質問してください。',
  },
};
